test: backup

diff --git a/.github/workflows/unit_test_linux_ubuntu.yaml b/.github/workflows/unit_test_linux_ubuntu.yaml
--- a/.github/workflows/unit_test_linux_ubuntu.yaml
+++ b/.github/workflows/unit_test_linux_ubuntu.yaml
@@ -1575,15 +1575,21 @@ jobs:
           # disable auto backup since it may affect below tests
           mo_ctl auto_backup disable
 
+          if mo_ctl auto_backup || mo_ctl auto_backup status; then
+              echo "Auto backup is not disabled as expected, exiting"
+              exit 1
+          fi
 
       - name: Test_11. Clean backup files (Auto)
         run: |
 
           echo "----------------------------------"
           echo "Set confs for auto backup"
-          mo_ctl set_conf BACKUP_CRON_SCHEDULE="*/2 * * * *"
+          # set auto backup to a specific timing
+          mo_ctl set_conf BACKUP_CRON_SCHEDULE="30 6 * * *"
           mo_ctl set_conf BACKUP_CLEAN_DAYS_BEFORE="0"
-          mo_ctl set_conf BACKUP_CLEAN_CRON_SCHEDULE="*/8 * * * *"
+          # set auto clean backup to once every 2 minute
+          mo_ctl set_conf BACKUP_CLEAN_CRON_SCHEDULE="*/2 * * * *"
 
          
           echo "----------------------------------"
@@ -1595,8 +1601,8 @@ jobs:
           mo_ctl auto_backup status         
 
           echo "----------------------------------"
-          echo "wait 130s for next auto backup to be performed"
-          sleep 130
+          echo "Backup manuallyu"
+          mo_ctl backup
 
           echo "----------------------------------"
           echo "Show backup path"
@@ -1610,8 +1616,8 @@ jobs:
           echo "----------------------------------"
           echo "Clean backup automatically"
           mo_ctl auto_backup
-          echo "Sleep 490s"
-          sleep 490
+          echo "Sleep 130s"
+          sleep 130
 
           echo "Show backup path: ls -lth ${{ env.BACKUP_PATH }}/${RUN_MONTH}/"
           ls -lth ${{ env.BACKUP_PATH }}/${RUN_MONTH}/
@@ -1628,41 +1634,38 @@ jobs:
               exit 1
           fi 
 
+          # for debuging
+          #echo "----------------------------------"
+          #echo "check log path ${MO_CTL_TOOL_LOG_PATH}/auto_backup/"
+          #ls -lth ${MO_CTL_TOOL_LOG_PATH}/auto_backup/
 
-          echo "----------------------------------"
-          echo "check log path ${MO_CTL_TOOL_LOG_PATH}/auto_backup/"
-          ls -lth ${MO_CTL_TOOL_LOG_PATH}/auto_backup/
+          #echo "----------------------------------"
+          #echo "check auto_backup logs: cat ${MO_CTL_TOOL_LOG_PATH}/auto_backup/*"
+          #cat ${MO_CTL_TOOL_LOG_PATH}/auto_backup/*
 
+          #echo "----------------------------------"
+          #echo "check log path ${MO_CTL_TOOL_LOG_PATH}/auto_clean_old_backup/"
+          #ls -lth ${MO_CTL_TOOL_LOG_PATH}/auto_clean_old_backup/
 
-          echo "----------------------------------"
-          echo "check auto_backup logs: cat ${MO_CTL_TOOL_LOG_PATH}/auto_backup/*"
-          cat ${MO_CTL_TOOL_LOG_PATH}/auto_backup/*
-
-          echo "----------------------------------"
-          echo "check log path ${MO_CTL_TOOL_LOG_PATH}/auto_clean_old_backup/"
-          ls -lth ${MO_CTL_TOOL_LOG_PATH}/auto_clean_old_backup/
-
-          echo "----------------------------------"
-          echo "show auto_clean_old_backup logs: cat ${MO_CTL_TOOL_LOG_PATH}/auto_clean_old_backup/*"
-          cat ${MO_CTL_TOOL_LOG_PATH}/auto_clean_old_backup/*
+          #echo "----------------------------------"
+          #echo "show auto_clean_old_backup logs: cat ${MO_CTL_TOOL_LOG_PATH}/auto_clean_old_backup/*"
+          #cat ${MO_CTL_TOOL_LOG_PATH}/auto_clean_old_backup/*
           
+          #echo "----------------------------------"
+          #echo "check cron.d path and file"
+          #ls -lth /etc/cron.d/
           
-          echo "----------------------------------"
-          echo "check cron.d path and file"
-          ls -lth /etc/cron.d/
+          #echo "----------------------------------"
+          #echo "content of file /etc/cron.d/mo_backup"
+          #cat /etc/cron.d/mo_backup
           
-          echo "----------------------------------"
-          echo "content of file /etc/cron.d/mo_backup"
-          cat /etc/cron.d/mo_backup
-          
-          echo "----------------------------------"
-          echo "content of file /etc/cron.d/mo_clean_old_backup"
-          cat /etc/cron.d/mo_clean_old_backup
+          #echo "----------------------------------"
+          #echo "content of file /etc/cron.d/mo_clean_old_backup"
+          #cat /etc/cron.d/mo_clean_old_backup
             
-          echo "----------------------------------"
-          echo "Disabling auto_backup"
-          mo_ctl auto_backup disable
-          if ! mo_ctl auto_backup; then
-              echo "auto_backup status failed as expected"
-          fi
-
+          #echo "----------------------------------"
+          #echo "Disabling auto_backup"
+          #mo_ctl auto_backup disable
+          #if ! mo_ctl auto_backup; then
+          #    echo "auto_backup status failed as expected"
+          #fi
